# Generated by Django 5.1.4 on 2024-12-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
